### ISSUE TITLE
Can't run GUI

### ISSUE THREAD

**Issue by plonibarploni** [argosopentech/argos-translate#127]
After installing with pip I get the following error when trying to run `argos-translate-gui`:
```
Traceback (most recent call last):
  File "/usr/local/bin/argos-translate-gui", line 3, in <module>
    from argostranslate import gui
  File "/usr/local/lib/python3.9/dist-packages/argostranslate/gui.py", line 10, in <module>
    from argostranslate import translate, package, settings, utils
  File "/usr/local/lib/python3.9/dist-packages/argostranslate/translate.py", line 5, in <module>
    import ctranslate2
  File "/home/username/.local/lib/python3.9/site-packages/ctranslate2/__init__.py", line 2, in <module>
    from ctranslate2.translator import Translator
ImportError: libctranslate2-c188fa63.so: cannot open shared object file: No such file or directory
```
I'm running Ubuntu 21.04.

**Comment by PJ-Finlay** [comment]
@guillaumekln any idea?

It works fine for me on Ubuntu 20.04, are you using an ARM processor?

**Comment by plonibarploni** [comment]
> are you using an ARM processor?

No.

**Comment by PJ-Finlay** [comment]
This is pretty strange then, it appears that CTranslate2 isn't able to fine the compiled binaries. Argos Translate uses `1.20.1` and [upgraded recently](https://github.com/argosopentech/argos-translate/commit/2d1a48ac8d7326c047f5aedf6d899de298e21369) which may be related.

**Comment by guillaumekln** [comment]
@plonibarploni Can you first try a clean reinstallation of the package?

```
pip install --ignore-installed --no-cache-dir argostranslate
```

**Comment by plonibarploni** [comment]
I tried a clean reinstallation and it still didn't work. But then I tried again in a virtual environment and it worked.
