### ISSUE TITLE
KeyError: 'score' on version 1.4.0

### ISSUE THREAD

**Issue by ivan-avalos** [argosopentech/argos-translate#151]
Hello! I'm getting this error when trying to perform any translation, both in CLI as in the GUI. I'm running version 1.4.0 on GNU/Linux 64 bits, Argos was working fine before the upgrade. Help.

```
Traceback (most recent call last):
  File "/usr/bin/argos-translate", line 5, in <module>
    cli.main()
  File "/usr/lib/python3.9/site-packages/argostranslate/cli.py", line 60, in main
    print(translation.translate(text_to_translate))
  File "/usr/lib/python3.9/site-packages/argostranslate/translate.py", line 54, in translate
    return self.hypotheses(input_text, num_hypotheses=1)[0].value
  File "/usr/lib/python3.9/site-packages/argostranslate/translate.py", line 276, in hypotheses
    translated_paragraph = self.underlying.hypotheses(
  File "/usr/lib/python3.9/site-packages/argostranslate/translate.py", line 161, in hypotheses
    apply_packaged_translation(
  File "/usr/lib/python3.9/site-packages/argostranslate/translate.py", line 411, in apply_packaged_translation
    cumulative_score += translated_batch[i]["score"]
KeyError: 'score'
```

**Comment by PJ-Finlay** [comment]
What version of CTranslate2 do you have installed? CTranslate2 2.0 disabled `return_scores` by default and isn't compatible with Argos Translate 1.4 (it is [supported in source](https://github.com/argosopentech/argos-translate/issues/133) though).

**Comment by ivan-avalos** [comment]
I would expect pip to install the correct version of CTranslate2 as a dependency of this specific version of Argos Translate. I have installed version 2.3.1.

**Comment by PJ-Finlay** [comment]
I'm not sure why that happened, probably something to do with the way it was upgraded? We specify a specific CTranslate2 version in requirements.txt so at least on a fresh install it should pull the correct version.
