### ISSUE TITLE
Compilation error in FreeBSD

### ISSUE THREAD

**Issue by lpvm** [argosopentech/argos-translate#191]
I'd like to compile argos-translate in a FreeBSD system.
It's supposed to be installed locally.
Perhaps there are some packages missing that could be installed globally.
Is there a list of packages to be installed, besides Python 3.8 and Qt5?

```
python3 -m pip install argostranslate
Defaulting to user installation because normal site-packages is not writeable
Collecting argostranslate
  Using cached argostranslate-1.5.2-py3-none-any.whl (30 kB)
Collecting PyQt5==5.15.4
  Using cached PyQt5-5.15.4.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp4cdt4aal
         cwd: /tmp/pip-install-953r8nsq/pyqt5_46a027e9f4f24884bf1b30ba03152645
    Complete output (31 lines):
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 130, in prepare_metadata_for_build_wheel
        return _get_wheel_metadata_from_wheel(backend, metadata_directory,
      File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 159, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/tmp/pip-build-env-jmsxirts/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/tmp/pip-build-env-jmsxirts/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/tmp/pip-build-env-jmsxirts/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 484, in setup
        self.apply_user_defaults(tool)
      File "project.py", line 63, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-jmsxirts/overlay/lib/python3.8/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-jmsxirts/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 230, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/tmp/pip-build-env-jmsxirts/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 66, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/8e/a4/d5e4bf99dd50134c88b95e926d7b81aad2473b47fde5e3e4eac2c69a8942/PyQt5-5.15.4.tar.gz#sha256=2a69597e0dd11caabe75fae133feca66387819fc9bc050f547e5551bce97e5be (from https://pypi.org/simple/pyqt5/) (requires-python:>=3.6). Command errored out with exit status 1: /usr/local/bin/python3 /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp4cdt4aal Check the logs for full command output.

```

**Comment by PJ-Finlay** [comment]
It looks like an issue installing PyQy which is used for the desktop app. If you're not using the desktop app you can try installing from source while removing the PyQt dependency.

**Comment by lpvm** [comment]
Thank you @PJ-Finlay.
As I'm not a Python developer, could you please tell me how to remove the PyQt dependency?

**Comment by PJ-Finlay** [comment]
Download:
```
git clone https://github.com/argosopentech/argos-translate.git
cd argos-translate

```

Remove `PyQt5` from `requirements.txt`.

Install in virtual environment:
```
virtualenv env
pip install -e .

```

I think that should work as long as you aren't using functionality that requires PyQt.

**Comment by lpvm** [comment]
Thank you for the help, but it seems that there's something wrong when doing `source env/bin/activate`:

```
/home/translate/argos-translate >source env/bin/activate
Missing '}'.
```

**Comment by PJ-Finlay** [comment]
Is the issue with creating the [virtual environment](https://docs.python.org/3/tutorial/venv.html)?

**Comment by lpvm** [comment]
`virtualenv env` seems to work fine.
The error comes from `source env/bin/activate`.

**Comment by PJ-Finlay** [comment]
That's strange, maybe Python virutal adornments aren't supported on FreeBSD? 

You can try deleting and trying again:
```
rm -rf env

```

You can also install to your default Python installation without a virutal environment. I recommend using the `-e` option so you can edit the source files.
```
pip install -e .

```

**Comment by pierotofy** [comment]
Try:

```
. venv/bin/activate
```

Also check which shell you're using (is it bash?)

**Comment by lpvm** [comment]
Well, part of the problem is solved, after installing bash as suggested.
I've recreated the virtual environment in bash, but now it's `pip install -e .` that is generating an error.

```
$ pip install -e .
Obtaining file:///usr/home/translate/argos-translate
ERROR: Could not find a version that satisfies the requirement ctranslate2==2.4.0 (from argostranslate) (from versions: none)
ERROR: No matching distribution found for ctranslate2==2.4.0
```

**Comment by PJ-Finlay** [comment]
Does [CTranslate2](https://github.com/OpenNMT/CTranslate2) support FreeBSD? @guillaumekln

**Comment by guillaumekln** [comment]
No, there are no binaries for FreeBSD.

**Comment by PJ-Finlay** [comment]
@lpvm you would need to compile and install CTranslate2 for FreeBSD to use Argos Translate.

**Comment by lpvm** [comment]
I've filed an issue for the CTranslate2 project, as I managed to compile the code (with help) but there's a core dump when running the example shown.

If/When the issue is solved, how should the manual installation be done for CTRanslate2.  Do I just need to copy the `translate` binary to the PATH?

**Comment by PJ-Finlay** [comment]
After you've installed CTranslate2 just install Argos Translate normally. You may want remove CTranslate2 from the Argos Translate requirements.txt too.

**Comment by lpvm** [comment]
I'm coming back after asking for help with CTranslate2.  The conclusion is that PyTorch and TensorFlow (the training frameworks) are not available on FreeBSD and guillaumekln suggested me to ask in here about the possibility to get one of your converted models.  
Is it possible to circumvent the CTranslate2 dependency with a converted model?

**Comment by lpvm** [comment]
I removed `ctranslate2` from `requirements.txt` and copied the built `translate` binary to a PATH location.
When doing `pip install -e .` from the `virtualenv`, 
```
$ pip install -e .
(...)
ERROR: Could not find a version that satisfies the requirement torch>=1.3.0 (from stanza)
ERROR: No matching distribution found for torch>=1.3.0
```

The package manager for FreeBSD doesn't find any `torch` python library.
Is this the end of the road for me?

**Comment by PJ-Finlay** [comment]
Argos Translate uses torch as part of Stanza to do sentence boundary detection but there is a workaround using [argostranslate.sbd](https://github.com/argosopentech/argos-translate/blob/e82c08398640d17f631100b8c1e65df9c6bbd116/argostranslate/sbd.py). Training requires torch but you can do inference with Argos Translate using only CTranslate2 and SentencePiece both of which are C++ libraries with a Python wrapper.

**Comment by lpvm** [comment]
I'd just like to setup a LibreTranslate service that needs argostranslate, but cannot do it without a how to, as I'm not a Python developer.

**Comment by PJ-Finlay** [comment]
If you're trying to run LibreTranslate and have CTranlate2 installed you should be able to:

Remove torch from Argos Translate requirements.txt.

```
export ARGOS_PACKAGE_INDEX="https://raw.githubusercontent.com/argosopentech/argospm-index-dev/main"
export ARGOS_STANZA_AVAILABLE=1
```


Install LibreTranslate

**Comment by lpvm** [comment]
When installing LibreTranslate it complains about `sentencepiece` from `argostranslate`:

```
Collecting sentencepiece==0.1.91
  Using cached sentencepiece-0.1.91.tar.gz (500 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1rs77ebc/sentencepiece_14f5ee88512b47998514fe8a60257328/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1rs77ebc/sentencepiece_14f5ee88512b47998514fe8a60257328/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-7ejme7ud
         cwd: /tmp/pip-install-1rs77ebc/sentencepiece_14f5ee88512b47998514fe8a60257328/
    Complete output (2 lines):
    /bin/sh: pkg-config: not found
    Failed to find sentencepiece pkgconfig
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ba/f6/520b56e5977f62aee48833da8b4ff2fdc2b10ebfa0dd78556b1d707d4086/sentencepiece-0.1.91.tar.gz#sha256=f9700cf607ea064d9fad34c751fbf49953dcc56fe68c54b277481aa0aec5c18f (from https://pypi.org/simple/sentencepiece/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement sentencepiece==0.1.91 (from argostranslate)
ERROR: No matching distribution found for sentencepiece==0.1.91
```

**Comment by PJ-Finlay** [comment]
SentencePiece must not support FreeBSD either. It's also a C++ library so you'll have to compile and install it from source like with CTranslate2.
