### ISSUE TITLE
ValueError when tokenize some inputs using `Vietnamese → English`

### ISSUE THREAD

**Issue by AutumnSun1996** [argosopentech/argos-translate#216]
A simple example:
```python
from argostranslate.translate import get_installed_languages

languages_list = get_installed_languages()
languages = {l.code: l for l in languages_list}

trans = languages['vi'].get_translation(languages['en'])

text = 'thuc luc di em trai <@!12345>'
res = trans.translate(text)
```

output:
```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    res = trans.translate(text)
  File "/home/qiushiyang/.local/lib/python3.7/site-packages/argostranslate/translate.py", line 52, in translate
    return self.hypotheses(input_text, num_hypotheses=1)[0].value
  File "/home/qiushiyang/.local/lib/python3.7/site-packages/argostranslate/translate.py", line 275, in hypotheses
    paragraph, num_hypotheses
  File "/home/qiushiyang/.local/lib/python3.7/site-packages/argostranslate/translate.py", line 160, in hypotheses
    self.pkg, paragraph, self.translator, num_hypotheses
  File "/home/qiushiyang/.local/lib/python3.7/site-packages/argostranslate/translate.py", line 385, in apply_packaged_translation
    stanza_sbd = stanza_pipeline(input_text)
  File "/home/qiushiyang/.local/lib/python3.7/site-packages/stanza/pipeline/core.py", line 166, in __call__
    doc = self.process(doc)
  File "/home/qiushiyang/.local/lib/python3.7/site-packages/stanza/pipeline/core.py", line 160, in process
    doc = self.processors[processor_name].process(doc)
  File "/home/qiushiyang/.local/lib/python3.7/site-packages/stanza/pipeline/tokenize_processor.py", line 88, in process
    no_ssplit=self.config.get('no_ssplit', False))
  File "/home/qiushiyang/.local/lib/python3.7/site-packages/stanza/models/tokenize/utils.py", line 165, in output_predictions
    st0 = text.index(part, char_offset) - char_offset
ValueError: substring not found
```

The bug only occurs for vi->en, thus should be related to the model used by stanza.

**Comment by PJ-Finlay** [comment]
Hmm, not sure. It does look like something with Stanza though. Do you know what type of inputs cause the issue? Also you can run with `export DEBUG=1` to see the sentence boundary detection output.

**Comment by yonilevineafs** [comment]
Did anyone ever figure out a solution to this? I'm running into the same issue with vi->en? @AutumnSun1996

**Comment by PJ-Finlay** [comment]
I reproduced this, it looks like it's an issue with Vietnamese sentence boundary detection.

The root cause could be an issue with [Stanza](https://stanfordnlp.github.io/stanza/) or the Stanza model was mispackaged somewhere.

- https://github.com/argosopentech/argos-train/blob/36c8cfc781eba1901b9a9d8fdea2e761a111dc69/argostrain/train.py#L178

``` 
File "/home/argosopentech/git/translate/env/lib/python3.8/site-packages/argostranslategui/gui.py", line 39, in run
    translated_text = self.translation_function()
  File "/home/argosopentech/git/translate/argostranslate/translate.py", line 52, in translate
    return self.hypotheses(input_text, num_hypotheses=1)[0].value
  File "/home/argosopentech/git/translate/argostranslate/translate.py", line 274, in hypotheses
    translated_paragraph = self.underlying.hypotheses(
  File "/home/argosopentech/git/translate/argostranslate/translate.py", line 159, in hypotheses
    apply_packaged_translation(
  File "/home/argosopentech/git/translate/argostranslate/translate.py", line 388, in apply_packaged_translation
    stanza_sbd = stanza_pipeline(input_text)
  File "/home/argosopentech/git/translate/env/lib/python3.8/site-packages/stanza/pipeline/core.py", line 166, in __call__
    doc = self.process(doc)
  File "/home/argosopentech/git/translate/env/lib/python3.8/site-packages/stanza/pipeline/core.py", line 160, in process
    doc = self.processors[processor_name].process(doc)
  File "/home/argosopentech/git/translate/env/lib/python3.8/site-packages/stanza/pipeline/tokenize_processor.py", line 85, in process
    _, _, _, document = output_predictions(None, self.trainer, batches, self.vocab, None,
  File "/home/argosopentech/git/translate/env/lib/python3.8/site-packages/stanza/models/tokenize/utils.py", line 163, in output_predictions
    st0 = text.index(part, char_offset) - char_offset
ValueError: substring not found
Aborted
```

**Comment by mubaldino** [comment]
Hello -- I'm testing this issue against the text sample above.

```
text = 'thuc luc di em trai <@!12345>'   # bug.
                               ^^^^^

text = 'thuc luc di em trai <@! 12345>'   # no bug.   Its litterally the conjoined punctuation + \w chars lead to tokenization issue
```

the substring where the problem occurs is the punct/number boundary.   This does not appear to have anything to do with vietnamese or any language.    STANZA v1.1 has specific post-processing tokenizer that cleans up sentence / paragraph chunking prior to feeding to predictor.

I tested further with newline and various punctuation situations and found that some amount of input text cleanup and conditioning allows the pathway for vietnamese to execute just fine.

nonetheless, for speed and for sustainability, I am looking forward to the spaCy and/or STANZA 1.10 upgrades.   There is no NLP suite that will have comprehensive language coverage, I think.  So a hybrid approach for a "NLP provider" may be the best model.

I needed one language - vietnamese. Very odd I tripped on this anomaly.

thanks for all this.
M
