### ISSUE TITLE
SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by aliciaviernes** [argosopentech/argos-translate#311]
Hello, I have the following problem:

```
Traceback (most recent call last):
  File "create_augs.py", line 4, in <module>
    from augmentation.main import text_augmentation2
  File "/home/USER/Code/show-attend-tell/augmentation/main.py", line 2, in <module>
    from .backtranslate import backtranslation
  File "/home/USER/Code/show-attend-tell/augmentation/backtranslate.py", line 6, in <module>
    from argostranslate import package, translate
  File "/home/aanagnostopoulou/.local/lib/python3.6/site-packages/argostranslate/package.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

I am running the code on Python 3.6 with the latest Argostranslate version. What could be the issue? Thanks!

**Comment by dingedi** [comment]
The latest versions of argos-translate require python 3.7 minimum. But we forgot to update the documentation I believe.
