### ISSUE TITLE
Error on windows 10 / Python 3.10 with basic example

### ISSUE THREAD

**Issue by maathieu** [argosopentech/argos-translate#332]
Hello, I have installed argos-translate with pip on a Windows 10 machine using Python 3.10. I then copied the [example on the docs page](https://github.com/argosopentech/argos-translate#examples) to see if it would run. But I get this error when running:

```
C:\Users\Somebody>python3.10 helloargos.py
Traceback (most recent call last):
  File "C:\Users\Somebody\helloargos.py", line 18, in <module>
    translatedText = argostranslate.translate.translate("Hello World", from_code, to_code)
  File "C:\Users\Somebody\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\argostranslate\translate.py", line 646, in translate
    return translation.translate(q)
  File "C:\Users\Somebody\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\argostranslate\translate.py", line 61, in translate
    return self.hypotheses(input_text, num_hypotheses=1)[0].value
  File "C:\Users\Somebody\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\argostranslate\translate.py", line 294, in hypotheses
    translated_paragraph = self.underlying.hypotheses(
  File "C:\Users\Somebody\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\argostranslate\translate.py", line 171, in hypotheses
    apply_packaged_translation(
  File "C:\Users\Somebody\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\argostranslate\translate.py", line 459, in apply_packaged_translation
    translated_batches = translator.translate_batch(
RuntimeError: Library cublas64_11.dll is not found or cannot be loaded
```

What am I supposed to do? Are there installation steps that are not documented?

Many thanks in advance :)

**Comment by maathieu** [comment]
Edit: it seems to be cuda related: when I remove the environment variable ARGOS_DEVICE_TYPE from my environment, the example script works.

**Comment by argosopentech** [comment]
I think this is an issue with CUDA:
```
RuntimeError: Library cublas64_11.dll is not found or cannot be loaded
```

Setting `ARGOS_DEVICE_TYPE=cpu` should also work.
