### ISSUE TITLE
SSLCertVerificationError Download failed for Arabic → English

### ISSUE THREAD

**Issue by michaelfeil** [argosopentech/argos-translate#347]
Below is a minimal reproduction script:

This crash occurs within docker, at build or run time of Libretranslate.
https://github.com/LibreTranslate/LibreTranslate/blob/main/scripts/install_models.py

```python
from pathlib import Path

from argostranslate import package, translate

import libretranslate.language


def boot(load_only=None, update_models=False):
    try:
        check_and_install_models(force=update_models, load_only_lang_codes=load_only)
    except Exception as e:
        print("Cannot update models (normal if you're offline): %s" % str(e))


def check_and_install_models(force=False, load_only_lang_codes=None):
    if len(package.get_installed_packages()) < 2 or force:
        # Update package definitions from remote
        print("Updating language models")
        package.update_package_index()

        # Load available packages from local package index
        available_packages = package.get_available_packages()
        print("Found %s models" % len(available_packages))

        # Download and install all available packages
        for available_package in available_packages:
            print(
                "Downloading %s (%s) ..."
                % (available_package, available_package.package_version)
            )
            available_package.install()

        # reload installed languages
        libretranslate.language.languages = translate.get_installed_languages()
        print(
            "Loaded support for %s languages (%s models total)!"
            % (len(translate.get_installed_languages()), len(available_packages))
        )

check_and_install_models()
```
```
 => ERROR [3/3] RUN ./venv/bin/python scripts/install_models.py                                                                                                                                                                                               2.3s
------
 > [3/3] RUN ./venv/bin/python scripts/install_models.py:
#0 1.899 (URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')),)
#0 1.947 (URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')),)
#0 1.966 (URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')),)
#0 1.985 (URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')),)
#0 1.986 Updating language models
#0 1.986 Found 60 models
#0 1.986 Downloading Arabic → English (1.0) ...
#0 1.986 Traceback (most recent call last):
#0 1.986   File "/app/scripts/install_models.py", line 15, in <module>
#0 1.986     check_and_install_models(force=True, load_only_lang_codes=lang_codes)
#0 1.986   File "/app/venv/lib/python3.10/site-packages/libretranslate/init.py", line 52, in check_and_install_models
#0 1.986     download_path = available_package.download()
#0 1.986   File "/app/venv/lib/python3.10/site-packages/argostranslate/package.py", line 258, in download
#0 1.986     raise Exception(f"Download failed for {str(self)}")
#0 1.986 Exception: Download failed for Arabic → English
------
Dockerfile:4
--------------------
   2 |     
   3 |     WORKDIR /app
   4 | >>> RUN ./venv/bin/python scripts/install_models.py
   5 |     
   6 |     EXPOSE 5000
```

**Comment by michaelfeil** [comment]
This is most likley a proxy error, as https://pub-dbae765fb25a4114aac1c88b90e94178.r2.dev/v1/translate-ar_en-1_0.argosmodel gets marked as pub-dbae765fb25a4114aac1c88b90e94178.r2.dev + ending .argosmodel are rather untypical.
