### ISSUE TITLE
Does not support Python 3.12

### ISSUE THREAD

**Issue by raffaem** [argosopentech/argos-translate#393]
Python 3.12 [remove support for distutils](https://docs.python.org/3.12/whatsnew/3.12.html#distutils).

Thus this package does not work with Python 3.12:
```
Traceback (most recent call last):
  File "/home/USERNAME/.pyenv/versions/argostranslate/bin/argos-translate", line 3, in <module>
    from argostranslate import cli
  File "/home/USERNAME/.pyenv/versions/3.12.1/envs/argostranslate/lib/python3.12/site-packages/argostranslate/cli.py", line 6, in <module>
    from argostranslate import translate
  File "/home/USERNAME/.pyenv/versions/3.12.1/envs/argostranslate/lib/python3.12/site-packages/argostranslate/translate.py", line 7, in <module>
    import stanza
  File "/home/USERNAME/.pyenv/versions/3.12.1/envs/argostranslate/lib/python3.12/site-packages/stanza/__init__.py", line 1, in <module>
    from stanza.pipeline.core import Pipeline
  File "/home/USERNAME/.pyenv/versions/3.12.1/envs/argostranslate/lib/python3.12/site-packages/stanza/pipeline/core.py", line 13, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
```

This should be specified in the README

**Comment by argosopentech** [comment]
https://github.com/argosopentech/argos-translate/issues/405
